// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWijnNpGIbAGk8VlawF6b0hXjIT2-WKxI',
    appId: '1:933946890106:web:03bc552362b2532b41e8c3',
    messagingSenderId: '933946890106',
    projectId: 'bolu-f55a2',
    authDomain: 'bolu-f55a2.firebaseapp.com',
    storageBucket: 'bolu-f55a2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7OQQtTPxdBQbV671v0CaBmQqkOJ9O_AI',
    appId: '1:933946890106:android:687803010d32cead41e8c3',
    messagingSenderId: '933946890106',
    projectId: 'bolu-f55a2',
    storageBucket: 'bolu-f55a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtgvuevhuDCcfx8uAkB7k0b3_sC_RxfGU',
    appId: '1:933946890106:ios:e8fa5030a964310e41e8c3',
    messagingSenderId: '933946890106',
    projectId: 'bolu-f55a2',
    storageBucket: 'bolu-f55a2.appspot.com',
    iosBundleId: 'com.hotelbooking.hotelBooking',
  );
}
